name: Distribute to AppStore Connect
run-name: Distribute to AppStore Connect by @${{ github.actor }}
description: "Distribute an .ipa to AppStore Connect"

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "The name of the artifact to upload"
        required: true
        type: string
      project-name:
        description: "The name of the project to build"
        required: true
        type: string
      project-directory:
        description: "The directory of the project to build (e.g. MyApp/)"
        required: false
        type: string
      production-branch-name:
        description: "The branch name to use for production environment"
        required: false
        type: string
        default: "main"
      create-tags:
        description: "Create tags for the release"
        required: true
        type: boolean
        default: true
    secrets:
      APP_STORE_CONNECT_ISSUER_ID:
        description: "The app store connect issuer id"
        required: true
      APP_STORE_CONNECT_KEY_IDENTIFIER:
        description: "The app store connect key identifier"
        required: true
      APP_STORE_CONNECT_PRIVATE_KEY:
        description: "The app store connect private key"
        required: true
      IOS_SIGNING_CERTIFICATE_BASE64:
        description: "The base64 encoded iOS signing certificate"
        required: true
      IOS_SIGNING_CERTIFICATE_PASSWORD:
        description: "The iOS signing certificate password"
        required: true
      IOS_PROVISIONING_PROFILE_BASE64:
        description: "The base64 encoded iOS provisioning profile"
        required: true
      IOS_KEYCHAIN_PASSWORD:
        description: "The iOS keychain password"
        required: true
      APP_STORE_APP_ID:
        description: "The iOS app store app id"
        required: true

jobs:
  build:
    runs-on: macos-latest

    env:
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      DIST_CERTIFICATE: ${{ secrets.IOS_SIGNING_CERTIFICATE_BASE64 }}
      DIST_CERTIFICATE_PASSWORD: ${{ secrets.IOS_SIGNING_CERTIFICATE_PASSWORD }}
      DIST_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
      APP_STORE_APP_ID: ${{ secrets.APP_STORE_APP_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./app

      - name: Install Codemagic CLI tools
        run: pip install codemagic-cli-tools

      - name: Publish the app to App Store Connect
        run: |
          APP_FILE=$(find $(pwd) -name "*.ipa")
          app-store-connect publish \
          --path "$APP_FILE"

      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: "./${{ inputs.project-directory}}${{ inputs.project-name}}.csproj"

      - name: Create tag
        if: ${{ inputs.create-tags == 'true' }}
        uses: rickstaa/action-create-tag@v1.7.2
        id: "tag_create"
        with:
          tag: "v${{ steps.package_version.outputs.version}}+${{github.run_number}}-ios"
          tag_exists_error: false
          message: "Latest release"
