name: .NET MAUI Build Android
description: "Workflow for building .NET MAUI applications for Android"
run-name: .NET MAUI Build Android Executed by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      project-name:
        description: "The name of the project to build"
        required: true
        type: string
      apk-filename:
        description: "The name of the APK file to upload"
        required: true
        type: string
      dotnet-version:
        description: "Version of .NET to use, defaults to 9.0.x"
        required: false
        type: string
        default: "9.0.x"
      dotnet-publish-version:
        description: "Version of .NET to use for publishing, defaults to 9.0"
        required: false
        type: string
        default: "9.0"
      java-version:
        description: "Version of Java to use"
        required: false
        type: string
        default: "17"
      project-directory:
        description: "The directory of the project to build (e.g. MyApp/)"
        required: false
        type: string
      appsettings-filename:
        description: "The name of the appsettings file"
        required: false
        type: string
      production-branch-name:
        description: "The branch name to use for production environment"
        required: false
        type: string
        default: "production"
      staging-branch-pattern:
        description: "The branch pattern to use for staging environment"
        required: false
        type: string
        default: "staging"
    secrets:
      ANDROID_KEYSTORE_ALIAS:
        description: "The Android keystore alias"
        required: true
      ANDROID_KEYSTORE_BASE64:
        description: "The base64 encoded Android keystore"
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        description: "The Android keystore password"
        required: true
      APPSETTINGS_BASE64:
        description: "The base64 encoded appsettings file"
        required: false

jobs:
  android-maui-build:
    environment: ${{ github.ref_name == inputs.production-branch-name && 'production' || contains(github.ref_name,inputs.staging-branch-pattern) && 'staging' || 'development' }}
    runs-on: windows-latest
    name: Build .NET MAUI Android
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Echo Environment
        run: echo ${{ github.ref_name == inputs.production-branch-name && 'production' || contains(github.ref_name,inputs.staging-branch-pattern) && 'staging' || 'development' }}

      - name: Load keystore from secrets
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "android-cert.keystore"
          fileDir: "./${{ inputs.project-directory}}"
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: ${{ inputs.java-version }}

      - name: Set up .NET for MAUI
        uses: samuelgustin/maui-workflows/.github/actions/dotnet/setup-maui@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          additional-restore-args: "${{ inputs.project-directory}}${{ inputs.project-name}}.csproj"
          maui-project-directory: ${{ inputs.project-directory }}

      - name: Pull Config From Secrets
        if: ${{ !contains(inputs.appsettings-filename, '') }}
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ${{ inputs.appsettings-filename }}
          fileDir: "./${{ inputs.project-directory}}"
          encodedString: ${{ secrets.APPSETTINGS_BASE64 }}

      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: "./${{ inputs.project-directory}}${{ inputs.project-name}}.csproj"

      - name: Build MAUI Android
        run: dotnet publish ${{ inputs.project-directory}}${{ inputs.project-name}}.csproj --no-restore -f:net${{ inputs.dotnet-publish-version }}-android -c:Release /p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} /p:AndroidSigningStorePass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} /p:AndroidBuildType="Production" /p:ApplicationDisplayVersion="${{ steps.package_version.outputs.version }}" /p:ApplicationVersion="${{ github.run_number }}"

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{inputs.apk-filename}}
          path: ${{ inputs.project-directory}}bin/Release/net${{ inputs.dotnet-publish-version }}-android/${{inputs.apk-filename}}
